### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dohliam** [codegolf/period1k#1]
Great entry as usual! I'd love to include this in [openjs1k](https://github.com/dohliam/openjs1k) as the first entry for 2016, and I was wondering if you would be willing to release it under an open license of some kind?

**Comment by tomhodgins** [comment]
Hi @dohliam, thanks for your interest. I looked at your openJS1K link and read the following:

> While on a larger level it is of course disappointing that all JS1K entries are not released with a free license, there are likely very good practical reasons for the organizers to leave copyright with the authors. That is not the problem.
> 
> The problem is that the contest rules do not require contestants to choose a license of some kind
> 
> ...
> 
> many (perhaps most?) authors do not license their work simply because they have never considered the possibility that their code might be useful to others outside of the context of the contest.

We're all huge fans of open-source, so it is possible that _after the contest is over_ we may update the license. For now, I think copyright is the most useful license for protecting our entry in the JS1K competition.

I think the fact that all entries are copyright to their authors is a key legal aspect of a competition like this. There's no way to hide your code, or stop people from taking your code _technologically_, so while the contest is being judged it's the laws of copyright that protect the author's entry _legally_.

We'll definitely revisit this when the contest is over. We also have some fun plans for paper distribution of the software in the future too! We're working on business card sized printouts of the source and rendered image :) If the table itself can't fit on a business card we might have to bump the format up to post card size - would you be interested in receiving a paper copy of the demo when we get those printed?

**Comment by dohliam** [comment]
Thanks for taking the time to respond. I totally understand if you don't want to use an open license or if you would rather wait until the competition is over (though a copyright notice would still be helpful in that case, even if it just says _all rights reserved_ -- since it would let people know that they don't need to ask about the license status).

The only reason I asked is because many of codegolf's entries have in the past included a public domain or similar license, e.g.:
- [minisimon](https://github.com/codegolf/minisimon/blob/gh-pages/LICENSE.md)
- [GameOfLife](https://github.com/codegolf/miniGameOfLife/blob/gh-pages/LICENCE.md)
- [pac-man](https://github.com/codegolf/pac-man/blob/master/LICENSE.txt)
- [minipoptiles](https://github.com/codegolf/minipoptiles/blob/gh-pages/LICENSE.md)
- [chip8](https://github.com/codegolf/chip8/blob/gh-pages/LICENCE.md)
- [braille-art](https://github.com/codegolf/braille-art/blob/gh-pages/LICENSE.md)

Actually, codegolf's work was one of the [original inspirations](https://github.com/dohliam/openjs1k#acknowledgements) for the openjs1k project. :smile:

**Comment by xem** [comment]
Hello @dohliam, sorry for the late answer. Thanks for taking us as an inspiration for your repo! As you can see, this project was updated yesterday with a brand new version. You can consider this code in MIT licence. Feel free to reuse it, but it's still nicer to cite us if you do ;)
Cheers
